spring.datasource.url=jdbc:sqlserver://sql1001.site4now.net:1433;databaseName=db_ac8d00_qlnsgiamao;encrypt=true;trustServerCertificate=true;
spring.datasource.username=db_ac8d00_qlnsgiamao_admin
spring.datasource.password=kawakipham14
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver